### ISSUE TITLE
Source Map Warnings?

### ISSUE THREAD

**Issue by acbart** [essserrr/crt-terminal#8]
Love this library! Seems pretty straightforward so far, although I'm getting a bunch (~39) of warnings related to the source map.

```
WARNING in ./node_modules/crt-terminal/dist/esm/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\acbart\Projects\spooky-mansion\node_modules\crt-terminal\src\hooks\terminal\useCommandScreen.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\acbart\Projects\spooky-mansion\node_modules\crt-terminal\src\hooks\terminal\useCommandScreen.ts'
 @ ./src/components/Terminal.tsx 7:0-75 13:21-34 17:30-38 19:13-21 20:14-22 24:33-41 45:10-23
 @ ./src/components/MainArea.tsx 8:0-42 51:41-53
 @ ./src/App.tsx 5:0-49 11:35-43
 @ ./src/index.tsx 8:0-24 12:33-36
```

These happen for basically all the source files. I was hoping just dropping the `src/` folder into the relevant `node_modules` would fix it, but it seems to actually be necessary to build it differently? My quick googling suggests you need to turn off source map generation or something when publishing. At least for anyone using CRA. Sorry if this is too vague, just wanted to pass it along in case it is helpful. Thanks for making this!

**Comment by essserrr** [comment]
@acbart Pls check if 1.0.12 update fixed your issue

**Comment by acbart** [comment]
It worked! Thank you so much :D This is perfect!
